name = "ankiconnect"
version = "1.1.0"
description = "A Gleam client for Anki Connect and Anki Connect Plus"
licences = ["Apache-2.0"]

repository = { type = "github", user = "lpil", repo = "ankiconnect" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
